language: node_js
os:
  - osx
  - linux
  - windows
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "D3IIBL4M32HOOGLwfEk27VSCNbQDkkmtTyvC1iE/qOeUFhtEpgiQeZCQmiN2SdnfrGKjSfINyGz0KvGMzxgeZ1RIqJbp3ZujhIY/v4HpUYvXBpVRbvsqmmaYmAUHBvrXVLAHD8WLJZ9z/0Cf0WwkXYg2onFtZbyZM9HSlEdZunk4MbScLb0uJoTnNPHNd2zX9m8Y+xwWrMNI+EqwBI7X5cVJjRUKq2LdCcOPcAIAyXt7U9OymC34Uf5dDKZHzVYTBPNkvp99MoLNUsznQmfII63/4SJH5ghi51AotbrhfFrrTDn+0pJi5zPt6bbXdsjYQup9Cu9DJlY5AY/ZPKuYw4eT1MIOIx+1qUXvbNgwjkZLCuslZQ0g4GyJJ2D350EcL1TUif5qKceq+nM0AvpEWVSwakFdB7KX3VPa5gIJoMReSy6fgQdAWHVWbfIjVptLStgtbbcdCTidkEKrOkslXOG5unbLLYky8vBbWwmGDbQHLvLEEbStfHh1zEtxQ11eMwBq7KdxDenVmX9/XhwMzAPOjDKcS6XTtQ4kLPB2czrbXnLXxuQ9+WVgKhm1PNVXYY8vWeXLjMqzy0L00BzVZ7lgWwJhYqnEvkYubjBeafiTgJuw7yVyryxv6E2cgo9EmSGRsX2LF7R4QU1iqh+vtTl+Oq1ymDqNJ5QPYhGteeI="
  api_key: # 58f0
    secure: "eic8Fo5he0mlwKowlk3auakPAkSnandrfQ+3CNZ2ApbSWHkp7cuEUYjjmiuvUTzpznDkz/j1eYrLQHW3gea1EfAmc3ftWmhJNUZ5dOotXsJwUxaWS6d4JjG9uyROWE2Gm8Umwn81Rto65IFoleqJ93O6cHDZBpVtrTNqVw3mU6pnAUS358yL+RrrS65ZAqIJpk6o1nQbREOgbT8NoHM8LFZ+VG9HulBhoM4XzFBXi5Hig3pNZvGYSrWsIzD8oa5o5mIa5tKy/EOgm/gH67oSoC3EDMxJJUxJDHsdeVGv7Pr7iNwt8bAIAGWUj+a4wihAY6MsJj0UCAuZdk2vS0iwKq11IeCwLWc7qgf7xb2UuruwEzxKGbu2VJqBZ3Xeep3QWi4cX7ON53bZ9jjiYBXb/+mBGrGdI9yrKmPNOVrVtBv9R0b3IzsBoBfH6slNNvMgqW16dp9QfGLxcx8eG9ai7qGi0El8D3whA4D9SBdlZU3m9YieCDzlxSMPyw0cXCxWYW0U3qrQLeMurR6SzhAx/4E3I2GNmW7ICxBAr6ABbn1jtt206S/riRukEBR5THce9wAHzNxiyyRchHe5VHYPnYMM/laftnntoh+xWTksDOYyEfb659lFAfF2dh1NNyV+Q7mkrSxedswtRmHPB+6hXIQXSsN4wvyByxS+v9iHXuA="
  on:
    tags: true
    node: lts/*
